# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo.xci
# IP: The module: 'riscq_init_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscq_init_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscq_init_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo.xci
# IP: The module: 'riscq_init_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscq_init_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscq_init_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
