# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gig_ethernet_pcs_pma_0 || ORIG_REF_NAME==gig_ethernet_pcs_pma_0} -quiet] -quiet
