# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku060-ffva1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/qbit/qubit_1.0/RISCQv1.1/project_1/project_1.cache/wt [current_project]
set_property parent.project_path F:/qbit/qubit_1.0/RISCQv1.1/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/qbit/qubit_1.0/RISCQv1.1/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/sitcp/SiTCP_XCKU_32K_BBT_V110.V
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/sitcp/SiTCP_top.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/sitcp/TIMER.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/sitcp/WRAP_SiTCP_GMII_XCKU_32K.V
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/data_ram.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/inst_rom.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/riscq.v
  F:/qbit/qubit_1.0/RISCQ/src/hdl/riscq_init.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/riscq_soc.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/rst_gen.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/user_regs.v
  F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/top.v
}
read_ip -quiet F:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/ip_0/synth/gig_ethernet_pcs_pma_0_gt.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/gig_ethernet_pcs_pma_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/gig_ethernet_pcs_pma_0/synth/gig_ethernet_pcs_pma_0_ooc.xdc]

read_ip -quiet F:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_rom/riscq_rom.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_rom/riscq_rom_ooc.xdc]

read_ip -quiet F:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_ram/riscq_ram.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_ram/riscq_ram_ooc.xdc]

read_ip -quiet f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/riscq_init_fifo/riscq_init_fifo_ooc.xdc]

read_ip -quiet f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width_ooc.xdc]

read_ip -quiet f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/vio_0/vio_0_ooc.xdc]

read_edif F:/qbit/qubit_1.0/RISCQv1.1/src/hdl/sitcp/SiTCP_XCKU_32K_BBT_V110.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcku060-ffva1156-2-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
