# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width.xci
# IP: The module: 'fifo_trans_width' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_trans_width'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_trans_width'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width.xci
# IP: The module: 'fifo_trans_width' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_trans_width'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/qbit/qubit_1.0/RISCQv1.1/ip_repos/fifo_trans_width/fifo_trans_width_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_trans_width'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
